# Site settings
title_left    : "Think"
title_right   : "space"
description   : ""
keywords      : "thinkspace kernel linux"
url           : https://legendary-acp.github.io # Replace with your GitHub username
baseurl       : "/thinkspace-kernel" # your repository name
cover         : "" # image uri like logo/cover image for site seo
comments_enabled  : false
disqus_shortname : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:month/:date/:title/
markdown    : kramdown
highlighter : rouge
source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed

# Author settings
author:
  name     : "Pradyuman" # Replace with your name

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - bourbon

# Pagination
paginate: 5
paginate_path: "/page:num/"

# navbar pages
# navbar:
#   - slug : about
#     title: About
#   - slug : blog
#     title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
  - ".sass-cache"
  - ".jekyll-cache"
  - "gemfiles"